ebay_clone-master/config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  get  "/items"                             =>  "items#index"
  get  "/items/new"                         =>  "items#new"
  post "/items"                             =>  "items#create"
  get  "/items/:id"                         =>  "items#show", as: 'item'
  post "/items/:item_id/purchases"          =>  "purchases#create", as: 'create_purchase'
  get  "/items/:item_id/purchases/:id"      =>  "purchases#show"
  get  "/users/new"                         =>  "users#new"
  post "/users"                             =>  "users#create"
  get  "/login"                             =>  "sessions#new"
  post "/login"                             =>  "sessions#create"
  get  "/logout"                            =>  "sessions#destroy"
  post "/items/:item_id/bids"               =>  "bids#create", as: 'create_bid'
  get "/items/:item_id/bids/:id"            =>  "bids#show"
  get "/tags/:id"                           =>  "tags#show", as: 'tag'
end

ebay_clone-master/app/views/layouts/_anonymous_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Ebay Clone</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"> <%= link_to("Log in", login_path) %></li>
      </ul>
      <ul class="nav navbar-nav">
        <li class="active"> <%= link_to("Item Marketplace", items_path) %></li>
      </ul>
    </div>
  </div>
</nav>

ebay_clone-master/app/views/layouts/_logged_in_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Ebay Clone</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"> <%= link_to("Log out", logout_path) %></li>
      </ul>
      <ul class="nav navbar-nav">
        <li class="active"> <%= link_to("Item Marketplace", items_path) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="navbar-text">Hello <%= current_user.username.capitalize %></li>
      </ul>
    </div>
  </div>
</nav>

ebay_clone-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EbayClone</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" %>
  </head>
  <body>

    <%= flash[:not_found] %>
    <% if current_user %>
      <%= render "layouts/logged_in_user" %>
    <% else %>
      <%= render "layouts/anonymous_user" %>
    <% end %>

    <%= yield %>

    <div class="footer navbar-fixed-bottom">
      <div class="container text-center">
        <p id="footer-text-container"> 8th Light Apprentice Project 2016</p>
      </div>
    </div>
  </body>
</html>